-- ============================================================
-- Migration: Categories, product slugs, is_active, product_attributes
-- ============================================================

-- 1. Categories table
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  parent_id bigint references public.categories(id) on delete set null,
  sort_order integer not null default 0,
  visible_frontend boolean not null default true,
  meta_title text,
  meta_description text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists categories_slug_idx on public.categories(slug);
create index if not exists categories_parent_id_idx on public.categories(parent_id);

-- 2. Seed categories
--    Hiện tại bán 2 dòng áo thun chính. Đồ mùa đông ẩn, sẵn sàng mở sau.
insert into public.categories (slug, name, parent_id, sort_order, visible_frontend, meta_title, meta_description)
values
  -- Visible now
  ('ao-thun-in-hinh',    'Áo Thun In Hình',    null, 1, true,
   'Áo Thun In Hình Streetwear | Nghe Hustle',
   'Bộ sưu tập áo thun in hình độc quyền từ Nghe Hustle – mỗi thiết kế là một câu chuyện.'),

  ('ao-thun-tron',       'Áo Thun Trơn',        null, 2, true,
   'Áo Thun Trơn Streetwear | Nghe Hustle',
   'Áo thun trơn chất lượng cao từ Nghe Hustle – basic nhưng không nhàm.'),

  -- Hidden now, ready for winter expansion
  ('hoodie',             'Hoodie',              null, 3, false,
   'Hoodie Streetwear | Nghe Hustle',
   'Hoodie streetwear Nghe Hustle – form rộng, chất nặng, giữ ấm cả mùa đông.'),

  ('ao-khoac',           'Áo Khoác',            null, 4, false,
   'Áo Khoác | Nghe Hustle',
   'Áo khoác streetwear từ Nghe Hustle – sắp ra mắt.'),

  ('quan',               'Quần',                null, 5, false,
   'Quần Streetwear | Nghe Hustle',
   'Quần streetwear Nghe Hustle – cargo, jogger và các thiết kế độc quyền.'),

  ('phu-kien',           'Phụ Kiện',            null, 6, false,
   'Phụ Kiện | Nghe Hustle',
   'Phụ kiện streetwear từ Nghe Hustle – sắp ra mắt.')
on conflict (slug) do nothing;

-- 3. Add slug, category_id, is_active to products table
alter table public.products
  add column if not exists slug text unique,
  add column if not exists category_id bigint references public.categories(id) on delete set null,
  add column if not exists is_active boolean not null default true;

create index if not exists products_slug_idx on public.products(slug);
create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists products_is_active_idx on public.products(is_active);

-- 4. Auto-generate slug fallback for existing products (admin nên đặt lại slug đúng sau)
update public.products
set slug = 'san-pham-' || id::text
where slug is null;

-- 5. Product attributes (EAV) table for flexible extra fields
create table if not exists public.product_attributes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  key text not null,
  value text not null,
  constraint product_attributes_unique unique (product_id, key)
);

create index if not exists product_attributes_product_id_idx on public.product_attributes(product_id);
