-- ============================================================
-- Migration: Lookbook sections table
-- ============================================================

create table if not exists public.lookbook_sections (
  id bigint generated by default as identity primary key,
  eyebrow text not null default '',
  title text not null,
  text text not null default '',
  product_id bigint references public.products(id) on delete set null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists lookbook_sections_sort_order_idx on public.lookbook_sections(sort_order);
create index if not exists lookbook_sections_product_id_idx on public.lookbook_sections(product_id);

-- Seed with current hardcoded sections (productId → actual DB product ids)
-- Admin should update product_id to match real product IDs after running
insert into public.lookbook_sections (eyebrow, title, text, product_id, sort_order, active)
values
  ('Editorial 01', 'Concrete Morning',
   'Những layer tối giản, chất liệu nặng tay và form rộng vừa đủ để đi từ phố đến studio mà không mất tinh thần streetwear gốc.',
   null, 1, true),
  ('Editorial 02', 'Late Shift Uniform',
   'Hoodie, cargo và tông đen được xử lý như một bộ đồng phục cho những ngày chạy deadline, rehearsal hoặc lang thang ngoài phố đêm.',
   null, 2, true),
  ('Editorial 03', 'Made To Move',
   'Phom dáng thoáng, vật liệu bền và bảng màu trầm giúp outfit trông gọn, chắc và hoạt động tốt ở nhịp sống hàng ngày.',
   null, 3, true);
