create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text not null,
  category text not null check (category in ('Tee', 'Hoodie', 'Pants')),
  description text not null,
  price integer not null check (price >= 0),
  old_price integer check (old_price is null or old_price >= price),
  tag text,
  tag_variant text check (tag_variant is null or tag_variant in ('gold', 'white', 'red', 'outline')),
  rating numeric(2, 1) not null default 5.0,
  review_count integer not null default 0,
  stock_count integer not null default 0,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.product_colors (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  hex text not null,
  bg_class text not null,
  position integer not null default 0
);

create table if not exists public.product_sizes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  size text not null check (size in ('S', 'M', 'L', 'XL', 'XXL')),
  available boolean not null default true,
  position integer not null default 0
);

create table if not exists public.product_specs (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  label text not null,
  value text not null,
  position integer not null default 0
);

create table if not exists public.product_features (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  value text not null,
  position integer not null default 0
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  alt text not null,
  bg_class text not null,
  icon_path text not null,
  image_url text,
  position integer not null default 0
);

create table if not exists public.vouchers (
  code text primary key,
  pct integer not null check (pct between 1 and 100),
  label text not null,
  description text not null,
  active boolean not null default true,
  max_uses integer,
  used_count integer not null default 0,
  expires_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  province text not null,
  district text,
  ward text,
  address text not null,
  note text,
  payment_method text not null check (payment_method in ('cod', 'qr')),
  voucher_code text references public.vouchers(code),
  discount_pct integer not null default 0,
  discount_label text,
  subtotal integer not null check (subtotal >= 0),
  discount_amount integer not null default 0 check (discount_amount >= 0),
  shipping_fee integer not null default 0 check (shipping_fee >= 0),
  total integer not null check (total >= 0),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'shipped', 'cancelled')),
  tracking_code text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint not null,
  product_name text not null,
  product_href text not null,
  variant_label text not null,
  qty integer not null check (qty > 0),
  unit_price integer not null check (unit_price >= 0),
  line_total integer not null check (line_total >= 0),
  bg_class text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists products_sort_idx on public.products(sort_order, id);
create index if not exists product_colors_product_id_idx on public.product_colors(product_id, position);
create index if not exists product_sizes_product_id_idx on public.product_sizes(product_id, position);
create index if not exists product_specs_product_id_idx on public.product_specs(product_id, position);
create index if not exists product_features_product_id_idx on public.product_features(product_id, position);
create index if not exists product_images_product_id_idx on public.product_images(product_id, position);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

alter table public.products enable row level security;
alter table public.product_colors enable row level security;
alter table public.product_sizes enable row level security;
alter table public.product_specs enable row level security;
alter table public.product_features enable row level security;
alter table public.product_images enable row level security;
alter table public.vouchers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products for select
using (true);

drop policy if exists "Public can read product colors" on public.product_colors;
create policy "Public can read product colors"
on public.product_colors for select
using (true);

drop policy if exists "Public can read product sizes" on public.product_sizes;
create policy "Public can read product sizes"
on public.product_sizes for select
using (true);

drop policy if exists "Public can read product specs" on public.product_specs;
create policy "Public can read product specs"
on public.product_specs for select
using (true);

drop policy if exists "Public can read product features" on public.product_features;
create policy "Public can read product features"
on public.product_features for select
using (true);

drop policy if exists "Public can read product images" on public.product_images;
create policy "Public can read product images"
on public.product_images for select
using (true);

drop policy if exists "Public can read vouchers" on public.vouchers;
create policy "Public can read vouchers"
on public.vouchers for select
using (active = true);

drop policy if exists "Authenticated can manage products" on public.products;
create policy "Authenticated can manage products"
on public.products for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can manage product colors" on public.product_colors;
create policy "Authenticated can manage product colors"
on public.product_colors for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can manage product sizes" on public.product_sizes;
create policy "Authenticated can manage product sizes"
on public.product_sizes for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can manage product specs" on public.product_specs;
create policy "Authenticated can manage product specs"
on public.product_specs for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can manage product features" on public.product_features;
create policy "Authenticated can manage product features"
on public.product_features for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can manage product images" on public.product_images;
create policy "Authenticated can manage product images"
on public.product_images for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can manage vouchers" on public.vouchers;
create policy "Authenticated can manage vouchers"
on public.vouchers for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can read orders" on public.orders;
create policy "Authenticated can read orders"
on public.orders for select
to authenticated
using (true);

drop policy if exists "Authenticated can update orders" on public.orders;
create policy "Authenticated can update orders"
on public.orders for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can read order items" on public.order_items;
create policy "Authenticated can read order items"
on public.order_items for select
to authenticated
using (true);
